function removetrTicks
box off
ax = axes('Position',get(gca,'Position'),...
    'Color','none',...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'XColor','k',...
    'YColor','k');
set(ax,'YTick', []);
set(ax,'XTick', []);
end
